name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permette di lanciarlo anche a mano

jobs:
  # STEP 1: Richiama il Security Gate (Job dipendente)
  check-security-gate:
    # Qui devi inserire il percorso esatto del file YAML che contiene la tua action di controllo
    uses: n-amico-test/vulnerable-to-gradle/.github/workflows/counter-sg.yml@b653ae55c073c7f260fc297415175f20e48246ec
    # Se il tuo workflow riutilizzabile ha bisogno del token, puoi passarlo così
    secrets: inherit
    with:
      force_release: true

  # STEP 2: Esegui il rilascio
  release-app:
    needs: check-security-gate 
    runs-on: ubuntu-latest
    steps:
      - name: Esecuzione rilascio
        run: |
          echo "Rilascio avvenuto con successo!"
